name: AWS Infra Provision with Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  Checkout_Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ap-southeast-1
  
  Setup_Terraform:
    runs-on: ubuntu-latest
    steps:        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
  
  Format_Plan_Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Format
        run: terraform fmt
      
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Validate
        run: terraform validate
  
  Apply_Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Apply
        run: terraform apply --auto-approve